openapi: 3.0.0
info:
  title: DreamTrip API
  description: API for authentication user and administration
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /api/v1/user/save:
    post:
      summary: Create new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: string
                example: "User created successfully"
  /api/v1/user/login:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDTO'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginMessage'
  /api/v1/admin/login:
    post:
      summary: Authenticate administrator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminLoginDTO'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminLoginMessage'
components:
  schemas:
    UserDTO:
      type: object
      properties:
        username:
          type: string
        userLastName:
          type: string
        email:
          type: string
        password:
          type: string
        phoneNumber:
          type: string
      required:
        - username
        - userLastName
        - email
        - password
    LoginDTO:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    AdminLoginDTO:
      type: object
      properties:
        email:
          type: string
        key:
          type: string
        password:
          type: string
      required:
        - email
        - key
        - password
    LoginMessage:
      type: object
      properties:
        message:
          type: string
        status:
          type: boolean
      required:
        - message
        - status
    AdminLoginMessage:
      type: object
      properties:
        message:
          type: string
        status:
          type: boolean
      required:
        - message
        - status
